Build with -nostdlib
Otherwise, the build fails on Ubuntu 16.04 with:

    undefined reference to `__stack_chk_guard'

since stack protection is turned on by default there.